name = "minnan-whatsapp-order-bot"
main = "src/index.js"
compatibility_date = "2026-09-04"

[[d1_databases]]
binding = "DB"
database_name = "minnan-orders"
database_id = "70c258f2-3a7f-4551-8fe3-581d8cb8c4cd"
migrations_dir = "migrations"
